### ISSUE TITLE
wrong var

### ISSUE THREAD

**Issue by Sangsom** [thisDOTname/datatables-date_range_filter#1]
On line 10 I guess there is typo it should be iMax_temp no iMin_temp. And for a date I have set it to current day like this:

var today = new Date();
var dd = today.getDate();
var mm = today.getMonth() + 1;
var yyyy = today.getFullYear();

if (dd<10)
    dd = '0'+dd;

if (mm<10)
    mm = '0'+mm;

today = mm+'/'+dd+'/'+yyyy;

var iMax_temp = $('#max').val();
if (iMax_temp == '') 
{
     iMax_temp =today;
}

**Comment by thisDOTname** [comment]
Thanks for pointing out the typo. I have fixed it now. Also, using the current date as default max date is the right thing to do. I didn't need it in the functionality for which I had written the code so I didn't include it but it should have been there anyways. Will update the code accordingly. Thanks again :+1:

**Comment by thisDOTname** [comment]
This issue has been fixed.

**Comment by Sangsom** [comment]
Thanks for your code which resolved problem for me :+1:  Cheers!

**Comment by thisDOTname** [comment]
No worries. Glad I could help :)
